version: '3'
services:
  mongo:
    image: mongo:4.4
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=testdb
    ports:
      - 27017:27017
  foodlogiq:
    build: .
    container_name: "foodlogiq"
    image: foodlogiq/latest
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - mongodb